[package]
name = "libnx-rs"
version = "0.1.0"
authors = ["ischeinkman <scheinkman.ilan@gmail.com>"]
links = "nx"

[lib]
crate_type = ["rlib"]

[build-dependencies]
bindgen = "0.37.4"

[features]
sysroot = []