[package]
name = "libnx"
version = "0.1.0"
authors = ["ischeinkman <scheinkman.ilan@gmail.com>", "XorTroll"]
links = "nx"

[lib]
crate_type = ["rlib"]

[build-dependencies]
bindgen = { version = "0.37.4", optional = true }

[features]
default = ["bindgen"]